/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistantMsg: typeof import('./src/components/chat/AssistantMsg.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ConversationItem: typeof import('./src/components/layout/ConversationItem.vue')['default']
    ConversationSidebar: typeof import('./src/components/layout/ConversationSidebar.vue')['default']
    FileItem: typeof import('./src/components/chat/FileItem.vue')['default']
    FileUpload: typeof import('./src/components/chat/FileUpload.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter/index.vue')['default']
    NavTitle: typeof import('./src/components/NavTitle/index.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NoData: typeof import('./src/components/noData.vue')['default']
    QuickQuestions: typeof import('./src/components/chat/QuickQuestions.vue')['default']
    UserMsg: typeof import('./src/components/chat/UserMsg.vue')['default']
  }
}
